// frontend/src/components/LogViewer.tsx
import React, { useState, useEffect } from 'react';
import { LogFilter } from './LogFilter';
import { LogTable } from './LogTable';
import { LogVisualizations } from './LogVisualizations';
import { fetchLogs } from '../api/logs';

interface LogViewerProps {
    platform: string;
}

export const LogViewer: React.FC<LogViewerProps> = ({ platform }) => {
    const [logs, setLogs] = useState([]);
    const [filters, setFilters] = useState({});
    const [view, setView] = useState<'table' | 'visual'>('table');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const loadLogs = async () => {
        try {
            setLoading(true);
            setError(null);
            const results = await fetchLogs({ ...filters, platform });
            setLogs(results);
        } catch (err) {
            setError('Failed to fetch logs');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadLogs();
    }, [platform]); // Reload when platform changes

    const handleFilterChange = async (newFilters: any) => {
        setFilters(newFilters);
        await loadLogs();
    };

    if (loading) return <div>Loading logs...</div>;
    if (error) return <div className="error">{error}</div>;

    return (
        <div className="log-viewer">
            <LogFilter onFilterChange={handleFilterChange} />
            
            <div className="view-controls">
                <button onClick={() => setView('table')}>Table View</button>
                <button onClick={() => setView('visual')}>Visualizations</button>
            </div>

            {view === 'table' ? (
                <LogTable logs={logs} />
            ) : (
                <LogVisualizations logs={logs} />
            )}
        </div>
    );
};

// src/app/components/log-viewer/log-viewer.component.ts
import { Component, Input, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LogFilterComponent } from '../log-filter/log-filter.component';
import { LogTableComponent } from '../log-table/log-table.component';
import { LogVisualizationsComponent } from '../log-visualizations/log-visualizations.component';
import { LogService } from '../../services/log.service';

@Component({
  selector: 'app-log-viewer',
  standalone: true,
  imports: [CommonModule, LogFilterComponent, LogTableComponent, LogVisualizationsComponent],
  template: `
    <div class="log-viewer">
      <app-log-filter (filterChange)="handleFilterChange($event)"></app-log-filter>
      
      <div class="view-controls">
        <button (click)="view.set('table')" [class.active]="view() === 'table'">
          Table View
        </button>
        <button (click)="view.set('visual')" [class.active]="view() === 'visual'">
          Visualizations
        </button>
      </div>

      @if (loading()) {
        <div>Loading logs...</div>
      } @else if (error()) {
        <div class="error">{{ error() }}</div>
      } @else {
        @if (view() === 'table') {
          <app-log-table [logs]="logs()"></app-log-table>
        } @else {
          <app-log-visualizations [logs]="logs()"></app-log-visualizations>
        }
      }
    </div>
  `,
  styles: [`
    .log-viewer {
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .view-controls {
      display: flex;
      gap: 10px;
    }

    .error {
      color: #dc3545;
      padding: 10px;
      border: 1px solid #dc3545;
      border-radius: 4px;
      background: #f8d7da;
    }
  `]
})
export class LogViewerComponent {
  @Input() platform!: string;
  
  private logService = inject(LogService);
  
  view = signal<'table' | 'visual'>('table');
  logs = signal<any[]>([]);
  loading = signal(false);
  error = signal<string | null>(null);
  filters = signal<any>({});

  ngOnInit() {
    this.loadLogs();
  }

  async loadLogs() {
    try {
      this.loading.set(true);
      this.error.set(null);
      const results = await this.logService.fetchLogs({
        ...this.filters(),
        platform: this.platform
      });
      this.logs.set(results);
    } catch (err) {
      this.error.set('Failed to fetch logs');
      console.error(err);
    } finally {
      this.loading.set(false);
    }
  }

  handleFilterChange(newFilters: any) {
    this.filters.set(newFilters);
    this.loadLogs();
  }
}
